export const FORMULARIO = 'FORMULARIO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS';
export const MOSTRAR_ERROR = 'MOSTRAR_ERROR';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const PROYECTO_ERROR = 'PROYECTO_ERROR';

export const TAREAS_PROYECTOS = 'TAREAS_PROYECTOS';
export const TAREAS_NUEVAS = 'TAREAS_NUEVAS';
export const TAREAS_VALIDAR = 'TAREAS_VALIDAR';
export const TAREAS_ELIMINAR = 'TAREAS_ELIMINAR';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const TAREA_ACTUALIZAR = 'TAREA_ACTUALIZAR';
export const TAREA_LIMPIAR = 'TAREA_LIMPIAR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
